### ISSUE TITLE
Faire le tris des images non utilisées

### ISSUE THREAD

**Issue by rednaks** [moztn/www-moztn#1]
Est ce que quelqu'un peut faire le tris des images du /home  ? j'ai remarqué qu'il y a bcp d'image non utilisées.
Merci de lister dans ce bug le nom de celles qu'on va garder pour chaque projet.

**Comment by rednaks** [comment]
Ou alors comme l'a suggéré @MedMack nettoyez les repos actuels c'est plus facile.

**Comment by MedMack** [comment]
moztn-home-page [master] : done

**Comment by Chaasof** [comment]
- homepage :+1: 
- contribute :+1: 
- Join us :+1: 
- ressources :+1: 
- styleguide :+1: 

So we can close this bug
