### ISSUE TITLE
Keep footer icons ?

### ISSUE THREAD

**Issue by MedMack** [moztn/www-moztn#20]
We have links of our social media all over the website, do we need to keep the icons in the footer ?

**Comment by rednaks** [comment]
where ? but even if we have them somewhere else, it's always good for people to see them, and keep in mind that the home page will be more visited thant the blog, it's our front page now.

**Comment by MedMack** [comment]
The footer is the same for all the page, icons won't be just in the main page. Since we have the contact information in /Contact do we need to keep them in the footer (of every other page) or not ?

**Comment by rednaks** [comment]
And what about users who don't want to contact us ? social media links should be accessible from anywhere to have better chances to get more followers.

**Comment by MedMack** [comment]
:+1: Right
