### ISSUE TITLE
Add contribute page

### ISSUE THREAD

**Issue by MedMack** [moztn/www-moztn#32]
Mock-up to follow
http://i.imgur.com/xuwWIRw.png

Fonts and styles used from : 
https://www.mozilla.org/en-US/contribute/
https://www.mozilla.org/en-US/contribute/signup/

**Comment by MedMack** [comment]
New Mock-up 
![main2](https://cloud.githubusercontent.com/assets/2369504/6966805/83dbd40e-d953-11e4-9769-15d7d2b56e81.png)

**Comment by medfiras** [comment]
depend de #46
