### ISSUE TITLE
Liens des ressource

### ISSUE THREAD

**Issue by rednaks** [moztn/www-moztn#43]
Il manque les liens pour chaque ressource, je pense qu'on doit aussi ajouter les liens dans les images, c'est un reflexe de cliquer sur les logos de nos jours.

**Comment by medfiras** [comment]
@rednaks need review to close this issue :)

**Comment by rednaks** [comment]
Le seul problème est styleguide, on peut mettre l'url github pour le moment je pense c mieux : 
https://moztn.github.io/styleguide/

**Comment by medfiras** [comment]
@rednaks  on créer un sous domaine pour styleguide ou on change l'url avec celle de github ?

**Comment by rednaks** [comment]
(y) puis on pointe vers le VPS puisque c'est statique :)
