### ISSUE TITLE
Social media links

### ISSUE THREAD

**Issue by rednaks** [moztn/www-moztn#45]
Quand on clique sur un des liens des réseaux sociaux, il y a un contours qui s'affice, est ce que c'est possible de l'enlever ?
![pointilles](https://cloud.githubusercontent.com/assets/1383161/7102382/dad04c8e-e076-11e4-8761-e773ffb5535c.png)

**Comment by medfiras** [comment]
le problème n'est pas seulement lors du click sur les liens de réseaux sociaux mais tout les liens. je régle ça ;)
