### ISSUE TITLE
FirefoxOS WebApp icons

### ISSUE THREAD

**Issue by rednaks** [moztn/www-moztn#49]
@MedMack we need two icons for the firefoxos web app `128x128` and `64x64` in `/static/webapp/icons/moztn-64.png` and `/static/webapp/icons/moztn-128.png`

**Comment by MedMack** [comment]
![moztn-128](https://cloud.githubusercontent.com/assets/2369504/7339992/3f714850-ec7a-11e4-9ddd-322e6c9c0880.png)
![moztn-64](https://cloud.githubusercontent.com/assets/2369504/7339993/3fa2ca42-ec7a-11e4-92ad-42b0b40b8ef4.png)

**Comment by MedMack** [comment]
This can be closed

**Comment by rednaks** [comment]
fixed in 76051baefa90ecc7c15d2604106485656cff419f
