### ISSUE TITLE
Le texte et les liens du slider présentent des erreurs

### ISSUE THREAD

**Issue by melekJe** [moztn/www-moztn#53]

**Comment by anefzaoui** [comment]
I WAS JUST ABOUT TO FILE THIS ONE :P

So, building on this;
We most likely need a semi-dynamic list of links for a website-wide scale, e.g. a json file with links and then pull from to their appropriate places. e.g.2 if the framework provides a paths mechanism, would be even better.

**Comment by rednaks** [comment]
@anefzaoui I was surprised we were not using routing already.

**Comment by rednaks** [comment]
@melekJe est ce que tu peux ajouter les corrections ?
