### ISSUE TITLE
when sending contribution message, user doesn't get a confirmation message

### ISSUE THREAD

**Issue by sidki** [moztn/www-moztn#54]
when sending contribution message, user doesn't get a confirmation message. So it appears that the message wasn't sent, which will may get the user to send more mails.

**Comment by Chaasof** [comment]
No need to write an other email! Le mail va être envoyé à un responsable du domaine donc on ajoute l'expediteur en cc dans ce mail. @sidki ?

**Comment by medfiras** [comment]
@Chaasof juste il veux afficher un petit message de confirmation pour dire que le message a été envoyer après le click sur le bouton "envoyer" (je pense)
