### ISSUE TITLE
Slider Links

### ISSUE THREAD

**Issue by za3zilla** [moztn/www-moztn#64]
Quand on clic sur les liens du slider ils s’ouvrent dans le même onglet même si le Ctrl est enfoncé et du coup l'utilisateur se perd, vu qu'il y a un lien qui mène à notre blog et d'autres mènent au site de mozilla.org. Notre but, c'est de le garder toujours dans le site même s'il parcourt de différentes pages du site.

**Comment by rednaks** [comment]
pour ouvrir un lien dans un nouvel onglet, il suffit d'ajouter `target="_blank"` dans la balise `a`, mais ça n'a pas marché sur le slider est ce qu'il y a une autre solution ? cc @medfiras
