### ISSUE TITLE
Enlever "Créer un compte sur Mozillians.org" sur la page /contribute

### ISSUE THREAD

**Issue by MedMack** [moztn/www-moztn#68]
On doit enlever ça et remplacer par Join ou autre chose
![screen shot 2015-06-02 at 13 04 16](https://cloud.githubusercontent.com/assets/2369504/7935321/f33374b6-0927-11e5-9216-b1d21642b78f.png)

**Comment by rednaks** [comment]
non ça va je pense

**Comment by MedMack** [comment]
Selon la nouvelle stratégie, un profile Mozillians est nécessaire pour rejoindre la communauté.
